// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dglhceyrwrqwoiahibyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbGhjZXlyd3Jxd29pYWhpYnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTk2NTMsImV4cCI6MjA2NTIzNTY1M30.5niZPcgOxCOK925f2-ZXQW25lgceJRyAHcnsK2EeIJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);