// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfkxbbhzpnouixxougxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtma3hiYmh6cG5vdWl4eG91Z3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzgxNTQsImV4cCI6MjA2NTQ1NDE1NH0.NTVsvQ4Au6bev815mtNZJgtnFe5CZkT0gyHWaGgnYVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);